osx_image: xcode61
language: objective-c
before_install: gem install cocoapods xcpretty -N
cache: cocoapods
podfile: Example/Podfile
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
script:
  - set -o pipefail && xcodebuild -workspace 'Example/TTTRegexAttributedLabelExample.xcworkspace' -scheme TTTRegexAttributedLabel -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6" clean build | xcpretty -c
  - pod lib lint --quick